"""
File:       gameboyISA.py
Purpose:    Contains the mnemonics and instruction size data for the LR35902 processor
Date:       10/23/2018
Author:     Will B.

Reference:
            http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html

"""
    
mnemonics = {
    '\x00' :    "NOP                    ",
    '\x01' :    "LD     BC      d16     ",
    '\x02' :    "LD     (BC)    A       ",
    '\x03' :    "INC    BC              ",
    '\x04' :    "INC    B               ",
    '\x05' :    "DEC    B               ",
    '\x06' :    "LD     B       d8      ",
    '\x07' :    "RLCA                   ",
    '\x08' :    "LD     (a16)   SP      ",
    '\x09' :    "ADD    HL      BC      ",
    '\x0a' :    "LD     A       (BC)    ",
    '\x0b' :    "DEC    BC              ",
    '\x0c' :    "INC    C               ",
    '\x0d' :    "DEC    C               ",
    '\x0e' :    "LD     C       d8      ",
    '\x0f' :    "RRCA                   ",
    '\x10' :    "STOP                   ",
    '\x11' :    "LD     DE      d16     ",
    '\x12' :    "LD     (DE)    d16     ",
    '\x13' :    "INC    DE              ",
    '\x14' :    "INC    D               ",
    '\x15' :    "DEC    D               ",
    '\x16' :    "LD     D       d8      ",
    '\x17' :    "RLA                    ",
    '\x18' :    "JR     r8              ",
    '\x19' :    "ADD    HL      DE      ",
    '\x1a' :    "LD     A       (DE)    ",
    '\x1b' :    "DEC    DE              ",
    '\x1c' :    "INC    E               ",
    '\x1d' :    "DEC    E               ",
    '\x1e' :    "LD     E       d8      ",
    '\x1f' :    "RRA                    ",
    '\x20' :    "JR     NZ      r8      ",
    '\x21' :    "LD     HL      d16     ",
    '\x22' :    "LD     (HL+)   A       ",
    '\x23' :    "INC    HL              ",
    '\x24' :    "INC    H               ",
    '\x25' :    "DEC    H               ",
    '\x26' :    "LD     H       d8      ",
    '\x27' :    "DAA                    ",
    '\x28' :    "JR     Z       r8      ",
    '\x29' :    "ADD    HL      HL      ",
    '\x2a' :    "LD     A       (HL+)   ",
    '\x2b' :    "DEC    SP              ",
    '\x2c' :    "INC    A               ",
    '\x2d' :    "DEC    A               ",
    '\x2e' :    "LD     A       d8      ",
    '\x2f' :    "CCF                    ",
    '\x30' :    "JR     NC      r8      ",
    '\x31' :    "LD     SP      d16     ",
    '\x32' :    "LD     (HL-)   A       ",
    '\x33' :    "INC    SP              ",
    '\x34' :    "INC    (HL)            ",
    '\x35' :    "DEC    (HL)            ",
    '\x36' :    "LD     (HL)    d8      ",
    '\x37' :    "SCF                    ",
    '\x38' :    "JR     C       r8      ",
    '\x39' :    "ADD    HL      SP      ",
    '\x3a' :    "LD     A       (HL-)   ",
    '\x3b' :    "DEC    SP              ",
    '\x3c' :    "INC    A               ",
    '\x3d' :    "DEC    A               ",
    '\x3e' :    "LD     A       d8      ",
    '\x3f' :    "CCF                    ",
    '\x40' :    "LD     B       B       ",
    '\x41' :    "LD     B       C       ",
    '\x42' :    "LD     B       D       ",
    '\x43' :    "LD     B       E       ",
    '\x44' :    "LD     B       H       ",
    '\x45' :    "LD     B       L       ",
    '\x46' :    "LD     B       (HL)    ",
    '\x47' :    "LD     B       A       ",
    '\x48' :    "LD     C       B       ",
    '\x49' :    "LD     C       C       ",
    '\x4a' :    "LD     C       D       ",
    '\x4b' :    "LD     C       E       ",
    '\x4c' :    "LD     C       H       ",
    '\x4d' :    "LD     C       L       ",
    '\x4e' :    "LD     C       (HL)    ",
    '\x4f' :    "LD     C       A       ",
    '\x50' :    "LD     D       B       ",
    '\x51' :    "LD     D       C       ",
    '\x52' :    "LD     D       D       ",
    '\x53' :    "LD     D       E       ",
    '\x54' :    "LD     D       H       ",
    '\x55' :    "LD     D       L       ",
    '\x56' :    "LD     D       (HL)    ",
    '\x57' :    "LD     D       A       ",
    '\x58' :    "LD     E       B       ",
    '\x59' :    "LD     E       C       ",
    '\x5a' :    "LD     E       D       ",
    '\x5b' :    "LD     E       E       ",
    '\x5c' :    "LD     E       H       ",
    '\x5d' :    "LD     E       L       ",
    '\x5e' :    "LD     E       (HL)    ",
    '\x5f' :    "LD     E       A       ",
    '\x60' :    "LD     H       B       ",
    '\x61' :    "LD     H       C       ",
    '\x62' :    "LD     H       D       ",
    '\x63' :    "LD     H       E       ",
    '\x64' :    "LD     H       H       ",
    '\x65' :    "LD     H       L       ",
    '\x66' :    "LD     H       (HL)    ",
    '\x67' :    "LD     H       A       ",
    '\x68' :    "LD     L       B       ",
    '\x69' :    "LD     L       C       ",
    '\x6a' :    "LD     L       D       ",
    '\x6b' :    "LD     L       E       ",
    '\x6c' :    "LD     L       H       ",
    '\x6d' :    "LD     L       L       ",
    '\x6e' :    "LD     L       (HL)    ",
    '\x6f' :    "LD     L       A       ",
    '\x70' :    "LD     (HL)    B       ",
    '\x71' :    "LD     (HL)    C       ",
    '\x72' :    "LD     (HL)    D       ",
    '\x73' :    "LD     (HL)    E       ",
    '\x74' :    "LD     (HL)    H       ",
    '\x75' :    "LD     (HL)    L       ",
    '\x76' :    "HALT                   ",
    '\x77' :    "LD     (HL)    A       ",
    '\x78' :    "LD     A       B       ",
    '\x79' :    "LD     A       C       ",
    '\x7a' :    "LD     A       D       ",
    '\x7b' :    "LD     A       E       ",
    '\x7c' :    "LD     A       H       ",
    '\x7d' :    "LD     A       L       ",
    '\x7e' :    "LD     A       (HL)    ",
    '\x7f' :    "LD     A       A       ",
    '\x80' :    "ADD    A       B       ",
    '\x81' :    "ADD    A       C       ",
    '\x82' :    "ADD    A       D       ",
    '\x83' :    "ADD    A       E       ",
    '\x84' :    "ADD    A       H       ",
    '\x85' :    "ADD    A       L       ",
    '\x86' :    "ADD    A       (HL)    ",
    '\x87' :    "ADD    A       A       ",
    '\x88' :    "ADC    A       B       ",
    '\x89' :    "ADC    A       C       ",
    '\x8a' :    "ADC    A       D       ",
    '\x8b' :    "ADC    A       E       ",
    '\x8c' :    "ADC    A       H       ",
    '\x8d' :    "ADC    A       L       ",
    '\x8e' :    "ADC    A       (HL)    ",
    '\x8f' :    "ADC    A       A       ",
    '\x90' :    "SUB    B               ",
    '\x91' :    "SUB    C               ",
    '\x92' :    "SUB    D               ",
    '\x93' :    "SUB    E               ",
    '\x94' :    "SUB    H               ",
    '\x95' :    "SUB    L               ",
    '\x96' :    "SUB    (HL)            ",
    '\x97' :    "SUB    A               ",
    '\x98' :    "SBC    A       B       ",
    '\x99' :    "SBC    A       C       ",
    '\x9a' :    "SBC    A       D       ",
    '\x9b' :    "SBC    A       E       ",
    '\x9c' :    "SBC    A       H       ",
    '\x9d' :    "SBC    A       L       ",
    '\x9e' :    "SBC    A       (HL)    ",
    '\x9f' :    "SBC    A       A       ",
    '\xa0' :    "AND    B               ",
    '\xa1' :    "AND    C               ",
    '\xa2' :    "AND    D               ",
    '\xa3' :    "AND    E               ",
    '\xa4' :    "AND    H               ",
    '\xa5' :    "AND    L               ",
    '\xa6' :    "AND    (HL)            ",
    '\xa7' :    "AND    A               ",
    '\xa8' :    "XOR    B               ",
    '\xa9' :    "XOR    C               ",
    '\xaa' :    "XOR    D               ",
    '\xab' :    "XOR    E               ",
    '\xac' :    "XOR    H               ",
    '\xad' :    "XOR    L               ",
    '\xae' :    "XOR    (HL)            ",
    '\xaf' :    "XOR    A               ",
    '\xb0' :    "OR     B               ",
    '\xb1' :    "OR     C               ",
    '\xb2' :    "OR     D               ",
    '\xb3' :    "OR     E               ",
    '\xb4' :    "OR     H               ",
    '\xb5' :    "OR     L               ",
    '\xb6' :    "OR     (HL)            ",
    '\xb7' :    "OR     A               ",
    '\xb8' :    "CP     B               ",
    '\xb9' :    "CP     C               ",
    '\xba' :    "CP     D               ",
    '\xbb' :    "CP     E               ",
    '\xbc' :    "CP     H               ",
    '\xbd' :    "CP     L               ",
    '\xbe' :    "CP     (HL)            ",
    '\xbf' :    "CP     A               ",
    '\xc0' :    "RET    NZ              ",
    '\xc1' :    "POP    BC              ",
    '\xc2' :    "JP     NZ      a16     ",
    '\xc3' :    "JP     a16             ",
    '\xc4' :    "CALL   NZ      a16     ",
    '\xc5' :    "PUSH   BC              ",
    '\xc6' :    "ADD    A       d8      ",
    '\xc7' :    "RST    00H             ",
    '\xc8' :    "RET    Z               ",
    '\xc9' :    "RET                    ",
    '\xca' :    "JP     Z       a16     ",
    '\xcb' :    "PREFIX CB              ",
    '\xcc' :    "CALL   Z       a16     ",
    '\xcd' :    "CALL   a16             ",
    '\xce' :    "ADC    A       d8      ",
    '\xcf' :    "RST    08H             ",
    '\xd0' :    "RET    NC              ",
    '\xd1' :    "POP    DE              ",
    '\xd2' :    "JP     NC      a16     ",
    '\xd3' :    "UNIMP                  ",
    '\xd4' :    "CALL   NC      a16     ",
    '\xd5' :    "PUSH   DE              ",
    '\xd6' :    "SUB    d8              ",
    '\xd7' :    "RST    10H             ",
    '\xd8' :    "RET    C               ",
    '\xd9' :    "RETI                   ",
    '\xda' :    "JP     C       a16     ",
    '\xdb' :    "UNIMP                  ",
    '\xdc' :    "CALL   C       a16     ",
    '\xdd' :    "UNIMP                  ",
    '\xde' :    "SBC    A       d8      ",
    '\xdf' :    "RST    18H             ",
    '\xe0' :    "LD     (a8)    A       ",
    '\xe1' :    "POP    HL              ",
    '\xe2' :    "LD     (C)     A       ",
    '\xe3' :    "UNIMP                  ",
    '\xe4' :    "UNIMP                  ",
    '\xe5' :    "PUSH   HL              ",
    '\xe6' :    "AND    d8              ",
    '\xe7' :    "RST    20H             ",
    '\xe8' :    "ADD    SP      r8      ",
    '\xe9' :    "JP     (HL)            ",
    '\xea' :    "LD     (a16)   A       ",
    '\xeb' :    "UNIMP                  ",
    '\xec' :    "UNIMP                  ",
    '\xed' :    "UNIMP                  ",
    '\xee' :    "XOR    d8              ",
    '\xef' :    "RST    28H             ",
    '\xf0' :    "LDH    A       (a8)    ",
    '\xf1' :    "POP    AF              ",
    '\xf2' :    "LD     A       (C)     ",
    '\xf3' :    "DI                     ",
    '\xf4' :    "UNIMP                  ",
    '\xf5' :    "PUSH   AF              ",
    '\xf6' :    "OR     d8              ",
    '\xf7' :    "RST    30H             ",
    '\xf8' :    "LD     HL      SP+r8   ",
    '\xf9' :    "LD     SP      HL      ",
    '\xfa' :    "LD     A       (a16)   ",
    '\xfb' :    "EI                     ",
    '\xfc' :    "UNIMP                  ",
    '\xfd' :    "UNIMP                  ",
    '\xfe' :    "CP     d8              ",
    '\xff' :    "RST    38H             "
    }


prefixCB = {
    '\x00' :    "RLC    B               ",
    '\x01' :    "RLC    C               ",
    '\x02' :    "RLC    D               ",
    '\x03' :    "RLC    E               ",
    '\x04' :    "RLC    H               ",
    '\x05' :    "RLC    L               ",
    '\x06' :    "RLC    (HL)            ",
    '\x07' :    "RLC    A               ",
    '\x08' :    "RRC    B               ",
    '\x09' :    "RRC    C               ",
    '\x0a' :    "RRC    D               ",
    '\x0b' :    "RRC    E               ",
    '\x0c' :    "RRC    H               ",
    '\x0d' :    "RRC    L               ",
    '\x0e' :    "RRC    (HL)            ",
    '\x0f' :    "RRC    A               ",
    '\x10' :    "RL     B               ",
    '\x11' :    "RL     C               ",
    '\x12' :    "RL     D               ",
    '\x13' :    "RL     E               ",
    '\x14' :    "RL     H               ",
    '\x15' :    "RL     L               ",
    '\x16' :    "RL     (HL)            ",
    '\x17' :    "RL     A               ",
    '\x18' :    "RR     B               ",
    '\x19' :    "RR     C               ",
    '\x1a' :    "RR     D               ",
    '\x1b' :    "RR     E               ",
    '\x1c' :    "RR     H               ",
    '\x1d' :    "RR     L               ",
    '\x1e' :    "RR     (HL)            ",
    '\x1f' :    "RR     A               ",
    '\x20' :    "SLA    B               ",
    '\x21' :    "SLA    C               ",
    '\x22' :    "SLA    D               ",
    '\x23' :    "SLA    E               ",
    '\x24' :    "SLA    H               ",
    '\x25' :    "SLA    L               ",
    '\x26' :    "SLA    (HL)            ",
    '\x27' :    "SLA    A               ",
    '\x28' :    "SRA    B               ",
    '\x29' :    "SRA    C               ",
    '\x2a' :    "SRA    D               ",
    '\x2b' :    "SRA    E               ",
    '\x2c' :    "SRA    H               ",
    '\x2d' :    "SRA    L               ",
    '\x2e' :    "SRA    (HL)            ",
    '\x2f' :    "SRA    A               ",
    '\x30' :    "SWAP   B               ",
    '\x31' :    "SWAP   C               ",
    '\x32' :    "SWAP   D               ",
    '\x33' :    "SWAP   E               ",
    '\x34' :    "SWAP   H               ",
    '\x35' :    "SWAP   L               ",
    '\x36' :    "SWAP   (HL)            ",
    '\x37' :    "SWAP   A               ",
    '\x38' :    "SRL    B               ",
    '\x39' :    "SRL    C               ",
    '\x3a' :    "SRL    D               ",
    '\x3b' :    "SRL    E               ",
    '\x3c' :    "SRL    H               ",
    '\x3d' :    "SRL    L               ",
    '\x3e' :    "SRL    (HL)            ",
    '\x3f' :    "SRL    A               ",
    '\x40' :    "BIT    0       B       ",
    '\x41' :    "BIT    0       C       ",
    '\x42' :    "BIT    0       D       ",
    '\x43' :    "BIT    0       E       ",
    '\x44' :    "BIT    0       H       ",
    '\x45' :    "BIT    0       L       ",
    '\x46' :    "BIT    0       (HL)    ",
    '\x47' :    "BIT    0       A       ",
    '\x48' :    "BIT    1       B       ",
    '\x49' :    "BIT    1       C       ",
    '\x4a' :    "BIT    1       D       ",
    '\x4b' :    "BIT    1       E       ",
    '\x4c' :    "BIT    1       H       ",
    '\x4d' :    "BIT    1       L       ",
    '\x4e' :    "BIT    1       (HL)    ",
    '\x4f' :    "BIT    1       A       ",
    '\x50' :    "BIT    2       B       ",
    '\x51' :    "BIT    2       C       ",
    '\x52' :    "BIT    2       D       ",
    '\x53' :    "BIT    2       E       ",
    '\x54' :    "BIT    2       H       ",
    '\x55' :    "BIT    2       L       ",
    '\x56' :    "BIT    2       (HL)    ",
    '\x57' :    "BIT    2       A       ",
    '\x58' :    "BIT    3       B       ",
    '\x59' :    "BIT    3       C       ",
    '\x5a' :    "BIT    3       D       ",
    '\x5b' :    "BIT    3       E       ",
    '\x5c' :    "BIT    3       H       ",
    '\x5d' :    "BIT    3       L       ",
    '\x5e' :    "BIT    3       (HL)    ",
    '\x5f' :    "BIT    3       A       ",
    '\x60' :    "BIT    4       B       ",
    '\x61' :    "BIT    4       C       ",
    '\x62' :    "BIT    4       D       ",
    '\x63' :    "BIT    4       E       ",
    '\x64' :    "BIT    4       H       ",
    '\x65' :    "BIT    4       L       ",
    '\x66' :    "BIT    4       (HL)    ",
    '\x67' :    "BIT    4       A       ",
    '\x68' :    "BIT    5       B       ",
    '\x69' :    "BIT    5       C       ",
    '\x6a' :    "BIT    5       D       ",
    '\x6b' :    "BIT    5       E       ",
    '\x6c' :    "BIT    5       H       ",
    '\x6d' :    "BIT    5       L       ",
    '\x6e' :    "BIT    5       (HL)    ",
    '\x6f' :    "BIT    5       A       ",
    '\x70' :    "BIT    6       B       ",
    '\x71' :    "BIT    6       C       ",
    '\x72' :    "BIT    6       D       ",
    '\x73' :    "BIT    6       E       ",
    '\x74' :    "BIT    6       H       ",
    '\x75' :    "BIT    6       L       ",
    '\x76' :    "BIT    6       (HL)    ",
    '\x77' :    "BIT    6       A       ",
    '\x78' :    "BIT    7       B       ",
    '\x79' :    "BIT    7       C       ",
    '\x7a' :    "BIT    7       D       ",
    '\x7b' :    "BIT    7       E       ",
    '\x7c' :    "BIT    7       H       ",
    '\x7d' :    "BIT    7       L       ",
    '\x7e' :    "BIT    7       (HL)    ",
    '\x7f' :    "BIT    7       A       ",
    '\x80' :    "RES    0       B       ",
    '\x81' :    "RES    0       C       ",
    '\x82' :    "RES    0       D       ",
    '\x83' :    "RES    0       E       ",
    '\x84' :    "RES    0       H       ",
    '\x85' :    "RES    0       L       ",
    '\x86' :    "RES    0       (HL)    ",
    '\x87' :    "RES    0       A       ",
    '\x88' :    "RES    1       B       ",
    '\x89' :    "RES    1       C       ",
    '\x8a' :    "RES    1       D       ",
    '\x8b' :    "RES    1       E       ",
    '\x8c' :    "RES    1       H       ",
    '\x8d' :    "RES    1       L       ",
    '\x8e' :    "RES    1       (HL)    ",
    '\x8f' :    "RES    1       A       ",
    '\x90' :    "RES    2       B       ",
    '\x91' :    "RES    2       C       ",
    '\x92' :    "RES    2       D       ",
    '\x93' :    "RES    2       E       ",
    '\x94' :    "RES    2       H       ",
    '\x95' :    "RES    2       L       ",
    '\x96' :    "RES    2       (HL)    ",
    '\x97' :    "RES    2       A       ",
    '\x98' :    "RES    3       B       ",
    '\x99' :    "RES    3       C       ",
    '\x9a' :    "RES    3       D       ",
    '\x9b' :    "RES    3       E       ",
    '\x9c' :    "RES    3       H       ",
    '\x9d' :    "RES    3       L       ",
    '\x9e' :    "RES    3       (HL)    ",
    '\x9f' :    "RES    3       A       ",
    '\xa0' :    "RES    4       B       ",
    '\xa1' :    "RES    4       C       ",
    '\xa2' :    "RES    4       D       ",
    '\xa3' :    "RES    4       E       ",
    '\xa4' :    "RES    4       H       ",
    '\xa5' :    "RES    4       L       ",
    '\xa6' :    "RES    4       (HL)    ",
    '\xa7' :    "RES    4       A       ",
    '\xa8' :    "RES    5       B       ",
    '\xa9' :    "RES    5       C       ",
    '\xaa' :    "RES    5       D       ",
    '\xab' :    "RES    5       E       ",
    '\xac' :    "RES    5       H       ",
    '\xad' :    "RES    5       L       ",
    '\xae' :    "RES    5       (HL)    ",
    '\xaf' :    "RES    5       A       ",
    '\xb0' :    "RES    6       B       ",
    '\xb1' :    "RES    6       C       ",
    '\xb2' :    "RES    6       D       ",
    '\xb3' :    "RES    6       E       ",
    '\xb4' :    "RES    6       H       ",
    '\xb5' :    "RES    6       L       ",
    '\xb6' :    "RES    6       (HL)    ",
    '\xb7' :    "RES    6       A       ",
    '\xb8' :    "RES    7       B       ",
    '\xb9' :    "RES    7       C       ",
    '\xba' :    "RES    7       D       ",
    '\xbb' :    "RES    7       E       ",
    '\xbc' :    "RES    7       H       ",
    '\xbd' :    "RES    7       L       ",
    '\xbe' :    "RES    7       (HL)    ",
    '\xbf' :    "RES    7       A       ",
    '\xc0' :    "SET    0       B       ",
    '\xc1' :    "SET    0       C       ",
    '\xc2' :    "SET    0       D       ",
    '\xc3' :    "SET    0       E       ",
    '\xc4' :    "SET    0       H       ",
    '\xc5' :    "SET    0       L       ",
    '\xc6' :    "SET    0       (HL)    ",
    '\xc7' :    "SET    0       A       ",
    '\xc8' :    "SET    1       B       ",
    '\xc9' :    "SET    1       C       ",
    '\xca' :    "SET    1       D       ",
    '\xcb' :    "SET    1       E       ",
    '\xcc' :    "SET    1       H       ",
    '\xcd' :    "SET    1       L       ",
    '\xce' :    "SET    1       (HL)    ",
    '\xcf' :    "SET    1       A       ",
    '\xd0' :    "SET    2       B       ",
    '\xd1' :    "SET    2       C       ",
    '\xd2' :    "SET    2       D       ",
    '\xd3' :    "SET    2       E       ",
    '\xd4' :    "SET    2       H       ",
    '\xd5' :    "SET    2       L       ",
    '\xd6' :    "SET    2       (HL)    ",
    '\xd7' :    "SET    2       A       ",
    '\xd8' :    "SET    3       B       ",
    '\xd9' :    "SET    3       C       ",
    '\xda' :    "SET    3       D       ",
    '\xdb' :    "SET    3       E       ",
    '\xdc' :    "SET    3       H       ",
    '\xdd' :    "SET    3       L       ",
    '\xde' :    "SET    3       (HL)    ",
    '\xdf' :    "SET    3       A       ",
    '\xe0' :    "SET    4       B       ",
    '\xe1' :    "SET    4       C       ",
    '\xe2' :    "SET    4       D       ",
    '\xe3' :    "SET    4       E       ",
    '\xe4' :    "SET    4       H       ",
    '\xe5' :    "SET    4       L       ",
    '\xe6' :    "SET    4       (HL)    ",
    '\xe7' :    "SET    4       A       ",
    '\xe8' :    "SET    5       B       ",
    '\xe9' :    "SET    5       C       ",
    '\xea' :    "SET    5       D       ",
    '\xeb' :    "SET    5       E       ",
    '\xec' :    "SET    5       H       ",
    '\xed' :    "SET    5       L       ",
    '\xee' :    "SET    5       (HL)    ",
    '\xef' :    "SET    5       A       ",
    '\xf0' :    "SET    6       B       ",
    '\xf1' :    "SET    6       C       ",
    '\xf2' :    "SET    6       D       ",
    '\xf3' :    "SET    6       E       ",
    '\xf4' :    "SET    6       H       ",
    '\xf5' :    "SET    6       L       ",
    '\xf6' :    "SET    6       (HL)    ",
    '\xf7' :    "SET    6       A       ",
    '\xf8' :    "SET    7       B       ",
    '\xf9' :    "SET    7       C       ",
    '\xfa' :    "SET    7       D       ",
    '\xfb' :    "SET    7       E       ",
    '\xfc' :    "SET    7       H       ",
    '\xfd' :    "SET    7       L       ",
    '\xfe' :    "SET    7       (HL)    ",
    '\xff' :    "SET    7       A       "
    }

mnemonicsSize = {
    '\x00' :    1,
    '\x01' :    3,
    '\x02' :    1,
    '\x03' :    1,
    '\x04' :    1,
    '\x05' :    1,
    '\x06' :    2,
    '\x07' :    1,

    '\x08' :    3,
    '\x09' :    1,
    '\x0a' :    1,
    '\x0b' :    1,
    '\x0c' :    1,
    '\x0d' :    1,
    '\x0e' :    2,
    '\x0f' :    1,

    '\x10' :    2,
    '\x11' :    3,
    '\x12' :    1,
    '\x13' :    1,
    '\x14' :    1,
    '\x15' :    1,
    '\x16' :    2,
    '\x17' :    1,

    '\x18' :    2,
    '\x19' :    1,
    '\x1a' :    1,
    '\x1b' :    1,
    '\x1c' :    1,
    '\x1d' :    1,
    '\x1e' :    2,
    '\x1f' :    1,

    '\x20' :    2,
    '\x21' :    3,
    '\x22' :    1,
    '\x23' :    1,
    '\x24' :    1,
    '\x25' :    1,
    '\x26' :    2,
    '\x27' :    1,

    '\x28' :    2,
    '\x29' :    1,
    '\x2a' :    1,
    '\x2b' :    1,
    '\x2c' :    1,
    '\x2d' :    1,
    '\x2e' :    2,
    '\x2f' :    1,

    '\x30' :    2,
    '\x31' :    3,
    '\x32' :    1,
    '\x33' :    1,
    '\x34' :    1,
    '\x35' :    1,
    '\x36' :    2,
    '\x37' :    1,

    '\x38' :    2,
    '\x39' :    1,
    '\x3a' :    1,
    '\x3b' :    1,
    '\x3c' :    1,
    '\x3d' :    1,
    '\x3e' :    2,
    '\x3f' :    1,

    '\x40' :    1,
    '\x41' :    1,
    '\x42' :    1,
    '\x43' :    1,
    '\x44' :    1,
    '\x45' :    1,
    '\x46' :    1,
    '\x47' :    1,

    '\x48' :    1,
    '\x49' :    1,
    '\x4a' :    1,
    '\x4b' :    1,
    '\x4c' :    1,
    '\x4d' :    1,
    '\x4e' :    1,
    '\x4f' :    1,

    '\x50' :    1,
    '\x51' :    1,
    '\x52' :    1,
    '\x53' :    1,
    '\x54' :    1,
    '\x55' :    1,
    '\x56' :    1,
    '\x57' :    1,

    '\x58' :    1,
    '\x59' :    1,
    '\x5a' :    1,
    '\x5b' :    1,
    '\x5c' :    1,
    '\x5d' :    1,
    '\x5e' :    1,
    '\x5f' :    1,

    '\x60' :    1,
    '\x61' :    1,
    '\x62' :    1,
    '\x63' :    1,
    '\x64' :    1,
    '\x65' :    1,
    '\x66' :    1,
    '\x67' :    1,

    '\x68' :    1,
    '\x69' :    1,
    '\x6a' :    1,
    '\x6b' :    1,
    '\x6c' :    1,
    '\x6d' :    1,
    '\x6e' :    1,
    '\x6f' :    1,

    '\x70' :    1,
    '\x71' :    1,
    '\x72' :    1,
    '\x73' :    1,
    '\x74' :    1,
    '\x75' :    1,
    '\x76' :    1,
    '\x77' :    1,

    '\x78' :    1,
    '\x79' :    1,
    '\x7a' :    1,
    '\x7b' :    1,
    '\x7c' :    1,
    '\x7d' :    1,
    '\x7e' :    1,
    '\x7f' :    1,

    '\x80' :    1,
    '\x81' :    1,
    '\x82' :    1,
    '\x83' :    1,
    '\x84' :    1,
    '\x85' :    1,
    '\x86' :    1,
    '\x87' :    1,

    '\x88' :    1,
    '\x89' :    1,
    '\x8a' :    1,
    '\x8b' :    1,
    '\x8c' :    1,
    '\x8d' :    1,
    '\x8e' :    1,
    '\x8f' :    1,

    '\x90' :    1,
    '\x91' :    1,
    '\x92' :    1,
    '\x93' :    1,
    '\x94' :    1,
    '\x95' :    1,
    '\x96' :    1,
    '\x97' :    1,

    '\x98' :    1,
    '\x99' :    1,
    '\x9a' :    1,
    '\x9b' :    1,
    '\x9c' :    1,
    '\x9d' :    1,
    '\x9e' :    1,
    '\x9f' :    1,

    '\xa0' :    1,
    '\xa1' :    1,
    '\xa2' :    1,
    '\xa3' :    1,
    '\xa4' :    1,
    '\xa5' :    1,
    '\xa6' :    1,
    '\xa7' :    1,

    '\xa8' :    1,
    '\xa9' :    1,
    '\xaa' :    1,
    '\xab' :    1,
    '\xac' :    1,
    '\xad' :    1,
    '\xae' :    1,
    '\xaf' :    1,

    '\xb0' :    1,
    '\xb1' :    1,
    '\xb2' :    1,
    '\xb3' :    1,
    '\xb4' :    1,
    '\xb5' :    1,
    '\xb6' :    1,
    '\xb7' :    1,

    '\xb8' :    1,
    '\xb9' :    1,
    '\xba' :    1,
    '\xbb' :    1,
    '\xbc' :    1,
    '\xbd' :    1,
    '\xbe' :    1,
    '\xbf' :    1,

    '\xc0' :    1,
    '\xc1' :    1,
    '\xc2' :    3,
    '\xc3' :    3,
    '\xc4' :    3,
    '\xc5' :    1,
    '\xc6' :    2,
    '\xc7' :    1,

    '\xc8' :    1,
    '\xc9' :    1,
    '\xca' :    3,
    '\xcb' :    1,
    '\xcc' :    3,
    '\xcd' :    3,
    '\xce' :    2,
    '\xcf' :    1,

    '\xd0' :    1,
    '\xd1' :    1,
    '\xd2' :    3,
    '\xd3' :    1,
    '\xd4' :    3,
    '\xd5' :    1,
    '\xd6' :    2,
    '\xd7' :    1,

    '\xd8' :    1,
    '\xd9' :    1,
    '\xda' :    3,
    '\xdb' :    1,
    '\xdc' :    3,
    '\xdd' :    1,
    '\xde' :    2,
    '\xdf' :    1,

    '\xe0' :    2,
    '\xe1' :    1,
    '\xe2' :    2,
    '\xe3' :    1,
    '\xe4' :    1,
    '\xe5' :    1,
    '\xe6' :    2,
    '\xe7' :    1,

    '\xe8' :    2,
    '\xe9' :    1,
    '\xea' :    3,
    '\xeb' :    1,
    '\xec' :    1,
    '\xed' :    1,
    '\xee' :    2,
    '\xef' :    1,

    '\xf0' :    2,
    '\xf1' :    1,
    '\xf2' :    2,
    '\xf3' :    1,
    '\xf4' :    1,
    '\xf5' :    1,
    '\xf6' :    2,
    '\xf7' :    1,

    '\xf8' :    2,
    '\xf9' :    1,
    '\xfa' :    3,
    '\xfb' :    1,
    '\xfc' :    1,
    '\xfd' :    1,
    '\xfe' :    2,
    '\xff' :    1 
    }


prefixCBSize = {
    '\x00' :    2,
    '\x01' :    2,
    '\x02' :    2,
    '\x03' :    2,
    '\x04' :    2,
    '\x05' :    2,
    '\x06' :    2,
    '\x07' :    2,
    '\x08' :    2,
    '\x09' :    2,
    '\x0a' :    2,
    '\x0b' :    2,
    '\x0c' :    2,
    '\x0d' :    2,
    '\x0e' :    2,
    '\x0f' :    2,
    '\x10' :    2,
    '\x11' :    2,
    '\x12' :    2,
    '\x13' :    2,
    '\x14' :    2,
    '\x15' :    2,
    '\x16' :    2,
    '\x17' :    2,
    '\x18' :    2,
    '\x19' :    2,
    '\x1a' :    2,
    '\x1b' :    2,
    '\x1c' :    2,
    '\x1d' :    2,
    '\x1e' :    2,
    '\x1f' :    2,
    '\x20' :    2,
    '\x21' :    2,
    '\x22' :    2,
    '\x23' :    2,
    '\x24' :    2,
    '\x25' :    2,
    '\x26' :    2,
    '\x27' :    2,
    '\x28' :    2,
    '\x29' :    2,
    '\x2a' :    2,
    '\x2b' :    2,
    '\x2c' :    2,
    '\x2d' :    2,
    '\x2e' :    2,
    '\x2f' :    2,
    '\x30' :    2,
    '\x31' :    2,
    '\x32' :    2,
    '\x33' :    2,
    '\x34' :    2,
    '\x35' :    2,
    '\x36' :    2,
    '\x37' :    2,
    '\x38' :    2,
    '\x39' :    2,
    '\x3a' :    2,
    '\x3b' :    2,
    '\x3c' :    2,
    '\x3d' :    2,
    '\x3e' :    2,
    '\x3f' :    2,
    '\x40' :    2,
    '\x41' :    2,
    '\x42' :    2,
    '\x43' :    2,
    '\x44' :    2,
    '\x45' :    2,
    '\x46' :    2,
    '\x47' :    2,
    '\x48' :    2,
    '\x49' :    2,
    '\x4a' :    2,
    '\x4b' :    2,
    '\x4c' :    2,
    '\x4d' :    2,
    '\x4e' :    2,
    '\x4f' :    2,
    '\x50' :    2,
    '\x51' :    2,
    '\x52' :    2,
    '\x53' :    2,
    '\x54' :    2,
    '\x55' :    2,
    '\x56' :    2,
    '\x57' :    2,
    '\x58' :    2,
    '\x59' :    2,
    '\x5a' :    2,
    '\x5b' :    2,
    '\x5c' :    2,
    '\x5d' :    2,
    '\x5e' :    2,
    '\x5f' :    2,
    '\x60' :    2,
    '\x61' :    2,
    '\x62' :    2,
    '\x63' :    2,
    '\x64' :    2,
    '\x65' :    2,
    '\x66' :    2,
    '\x67' :    2,
    '\x68' :    2,
    '\x69' :    2,
    '\x6a' :    2,
    '\x6b' :    2,
    '\x6c' :    2,
    '\x6d' :    2,
    '\x6e' :    2,
    '\x6f' :    2,
    '\x70' :    2,
    '\x71' :    2,
    '\x72' :    2,
    '\x73' :    2,
    '\x74' :    2,
    '\x75' :    2,
    '\x76' :    2,
    '\x77' :    2,
    '\x78' :    2,
    '\x79' :    2,
    '\x7a' :    2,
    '\x7b' :    2,
    '\x7c' :    2,
    '\x7d' :    2,
    '\x7e' :    2,
    '\x7f' :    2,
    '\x80' :    2,
    '\x81' :    2,
    '\x82' :    2,
    '\x83' :    2,
    '\x84' :    2,
    '\x85' :    2,
    '\x86' :    2,
    '\x87' :    2,
    '\x88' :    2,
    '\x89' :    2,
    '\x8a' :    2,
    '\x8b' :    2,
    '\x8c' :    2,
    '\x8d' :    2,
    '\x8e' :    2,
    '\x8f' :    2,
    '\x90' :    2,
    '\x91' :    2,
    '\x92' :    2,
    '\x93' :    2,
    '\x94' :    2,
    '\x95' :    2,
    '\x96' :    2,
    '\x97' :    2,
    '\x98' :    2,
    '\x99' :    2,
    '\x9a' :    2,
    '\x9b' :    2,
    '\x9c' :    2,
    '\x9d' :    2,
    '\x9e' :    2,
    '\x9f' :    2,
    '\xa0' :    2,
    '\xa1' :    2,
    '\xa2' :    2,
    '\xa3' :    2,
    '\xa4' :    2,
    '\xa5' :    2,
    '\xa6' :    2,
    '\xa7' :    2,
    '\xa8' :    2,
    '\xa9' :    2,
    '\xaa' :    2,
    '\xab' :    2,
    '\xac' :    2,
    '\xad' :    2,
    '\xae' :    2,
    '\xaf' :    2,
    '\xb0' :    2,
    '\xb1' :    2,
    '\xb2' :    2,
    '\xb3' :    2,
    '\xb4' :    2,
    '\xb5' :    2,
    '\xb6' :    2,
    '\xb7' :    2,
    '\xb8' :    2,
    '\xb9' :    2,
    '\xba' :    2,
    '\xbb' :    2,
    '\xbc' :    2,
    '\xbd' :    2,
    '\xbe' :    2,
    '\xbf' :    2,
    '\xc0' :    2,
    '\xc1' :    2,
    '\xc2' :    2,
    '\xc3' :    2,
    '\xc4' :    2,
    '\xc5' :    2,
    '\xc6' :    2,
    '\xc7' :    2,
    '\xc8' :    2,
    '\xc9' :    2,
    '\xca' :    2,
    '\xcb' :    2,
    '\xcc' :    2,
    '\xcd' :    2,
    '\xce' :    2,
    '\xcf' :    2,
    '\xd0' :    2,
    '\xd1' :    2,
    '\xd2' :    2,
    '\xd3' :    2,
    '\xd4' :    2,
    '\xd5' :    2,
    '\xd6' :    2,
    '\xd7' :    2,
    '\xd8' :    2,
    '\xd9' :    2,
    '\xda' :    2,
    '\xdb' :    2,
    '\xdc' :    2,
    '\xdd' :    2,
    '\xde' :    2,
    '\xdf' :    2,
    '\xe0' :    2,
    '\xe1' :    2,
    '\xe2' :    2,
    '\xe3' :    2,
    '\xe4' :    2,
    '\xe5' :    2,
    '\xe6' :    2,
    '\xe7' :    2,
    '\xe8' :    2,
    '\xe9' :    2,
    '\xea' :    2,
    '\xeb' :    2,
    '\xec' :    2,
    '\xed' :    2,
    '\xee' :    2,
    '\xef' :    2,
    '\xf0' :    2,
    '\xf1' :    2,
    '\xf2' :    2,
    '\xf3' :    2,
    '\xf4' :    2,
    '\xf5' :    2,
    '\xf6' :    2,
    '\xf7' :    2,
    '\xf8' :    2,
    '\xf9' :    2,
    '\xfa' :    2,
    '\xfb' :    2,
    '\xfc' :    2,
    '\xfd' :    2,
    '\xfe' :    2,
    '\xff' :    2
    }
